version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      - mongodb
    environment:
      - OPENAI_API_KEY

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_SERVER_PORT:${PORT}
        - REACT_APP_API_ROOT:/graphql
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - ./client:/app

volumes:
  db:
