version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app

volumes:
  db:
